# Generated by Django 4.1.1 on 2023-07-19 20:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_producto_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=django_countries.fields.CountryField(default='CL', max_length=2),
        ),
    ]
