# Generated by Django 4.1.1 on 2023-07-19 20:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_directorgeneral_especialidad_laboratorio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=django_countries.fields.CountryField(default='CL', max_length=2),
        ),
    ]
