# Generated by Django 4.1.1 on 2023-07-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_alter_laboratorio_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
