# Generated by Django 4.1.1 on 2023-07-19 20:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_directorgeneral_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
