# Generated by Django 4.1.1 on 2023-07-19 20:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_remove_laboratorio_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
